spring:
  application:
    name: search-service
  data:
    elasticsearch:
#      cluster-nodes: 192.168.244.202:9300
      cluster-nodes: 121.37.130.94:9300
      cluster-name: my-application
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10011/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
server:
  port: 8083